package es.eternalshadow.enums;

public enum Reliquias {
    ESPADA_DEL_AURORA,
    ORBE_DEL_CAOS,
    ARMADURA_DEL_FENIX,
    CAPA_DE_SOMBRAS,
    BASTON_DEL_ARCHIMAGO,
    ESCUDO_DEL_ULTIMO_BASTION,
    MAPA_VIVIENTE,
    BRUJULA_DEL_MAS_ALLA,
    ANILLO_DE_LA_CONDENA,
    MASCARA_DEL_OLVIDO,
    LIBRO_DE_LOS_SECRETOS,
    LINTERNA_DE_ALMAS,
    LLAVE_DE_LOS_PLANOS,
    CORAZON_DE_LA_NADA,
    OJO_DEL_CREADOR
}
